breaking: http-client expected to have .create fn
ipfs-shipyard/ipfs-provider pull request #38
Opened 2021-08-24 09:17 UTC by hacdias

License: MIT
Signed-off-by: Henrique Dias <hacdias@gmail.com>

2021-08-31 14:52 UTC, lidel requested changes

2021-08-31 14:52 UTC, lidel commented on src/providers/http-client.js
> +    const ipfs = httpClient.create({ ...options, ...clientOptions(apiAddress) })
A bit unfortunate that this will break old code in demos and hackpads that naively load the latest version:

```html
<script src="https://cdn.jsdelivr.net/npm/ipfs-core/dist/index.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ipfs-http-client/dist/index.min.js"></script>
```

Can we add the old version inside the catch block, as a fallback attempt?
(ipfs-provider aims to smooth out rough edges introduced by breaking changes in js-ipfs*)

2021-09-01 10:41 UTC, hacdias commented on src/providers/http-client.js
> +    const ipfs = httpClient.create({ ...options, ...clientOptions(apiAddress) })
Done. It's now backwards compatible!

2021-09-01 16:07 UTC, lidel approved these changes
Thanks! Will release as v2.0.2 shortly

2021-09-01 16:12 UTC, merged

2021-09-01 16:18 UTC, lidel commented
Shipped in v2.1.0